// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7syl0NYZo1RAOK9ieMg9jrCz9x8_4934',
    appId: '1:941591449824:android:fbb5d29bf3f7652ff10085',
    messagingSenderId: '941591449824',
    projectId: 'randomvideo-b0b25',
    databaseURL: 'https://randomvideo-b0b25-default-rtdb.firebaseio.com',
    storageBucket: 'randomvideo-b0b25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkg8fD4rXtyuzJgi_UFE0gFbehFmPKixw',
    appId: '1:941591449824:ios:5150a141f35ef0cbf10085',
    messagingSenderId: '941591449824',
    projectId: 'randomvideo-b0b25',
    databaseURL: 'https://randomvideo-b0b25-default-rtdb.firebaseio.com',
    storageBucket: 'randomvideo-b0b25.firebasestorage.app',
    iosBundleId: 'com.winloop.vidmatch',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSL8ntUScCDRGUVIK0G8X5MUjQtgdJieA',
    appId: '1:941591449824:web:653b65e4f1886cfdf10085',
    messagingSenderId: '941591449824',
    projectId: 'randomvideo-b0b25',
    authDomain: 'randomvideo-b0b25.firebaseapp.com',
    databaseURL: 'https://randomvideo-b0b25-default-rtdb.firebaseio.com',
    storageBucket: 'randomvideo-b0b25.firebasestorage.app',
    measurementId: 'G-68REP886BV',
  );

}